import json
from datetime import datetime

signals = [
    {"source":"google_trends","term":"ginger shot","signal_value":-6,"snippet":"Google Trends: 'ginger shot' avg interest=26.1/100, growth -6% (last 4 wks vs prior 12)","timestamp":"2026-04-17T00:00:00","metadata":{"timeframe":"today 3-m","query_type":"interest_over_time","avg_interest":26.1}},
    {"source":"google_trends","term":"ginseng supplement","signal_value":-15,"snippet":"Google Trends: 'ginseng supplement' avg interest=12.4/100, growth -15%","timestamp":"2026-04-17T00:00:00","metadata":{"timeframe":"today 3-m","query_type":"interest_over_time","avg_interest":12.4}},
    {"source":"google_trends","term":"lion's mane","signal_value":-5,"snippet":"Google Trends: 'lions mane' avg interest=54.2/100, growth -5%","timestamp":"2026-04-17T00:00:00","metadata":{"timeframe":"today 3-m","query_type":"interest_over_time","avg_interest":54.2}},
    {"source":"google_trends","term":"ashwagandha gummy","signal_value":-18,"snippet":"Google Trends: 'ashwagandha gummy' avg interest=31.0/100, growth -18%","timestamp":"2026-04-17T00:00:00","metadata":{"timeframe":"today 3-m","query_type":"interest_over_time","avg_interest":31.0}},
    {"source":"google_trends","term":"reishi tea","signal_value":0,"snippet":"Google Trends: 'reishi tea' avg interest=22.0/100, growth 0%","timestamp":"2026-04-17T00:00:00","metadata":{"timeframe":"today 3-m","query_type":"interest_over_time","avg_interest":22.0}},
    {"source":"google_trends","term":"mushroom coffee","signal_value":8,"snippet":"Google Trends: 'mushroom coffee' avg interest=61.0/100, growth +8%","timestamp":"2026-04-17T00:00:00","metadata":{"timeframe":"today 3-m","query_type":"interest_over_time","avg_interest":61.0}},
    {"source":"google_trends","term":"moringa powder","signal_value":5,"snippet":"Google Trends: 'moringa powder' avg interest=18.0/100, growth +5%","timestamp":"2026-04-17T00:00:00","metadata":{"timeframe":"today 3-m","query_type":"interest_over_time","avg_interest":18.0}},
    {"source":"google_trends","term":"pandan snack","signal_value":12,"snippet":"Google Trends: 'pandan snack' avg interest=9.0/100, growth +12%","timestamp":"2026-04-17T00:00:00","metadata":{"timeframe":"today 3-m","query_type":"interest_over_time","avg_interest":9.0}},
    {"source":"google_trends","term":"yuzu candy","signal_value":0,"snippet":"Google Trends: 'yuzu candy' avg interest=7.0/100, growth 0%","timestamp":"2026-04-17T00:00:00","metadata":{"timeframe":"today 3-m","query_type":"interest_over_time","avg_interest":7.0}},
    {"source":"google_trends","term":"ube latte","signal_value":-20,"snippet":"Google Trends: 'ube latte' avg interest=24.0/100, growth -20%","timestamp":"2026-04-17T00:00:00","metadata":{"timeframe":"today 3-m","query_type":"interest_over_time","avg_interest":24.0}},
    {"source":"google_trends","term":"tempeh chips","signal_value":28,"snippet":"Google Trends: 'tempeh chips' avg interest=11.0/100, growth +28%","timestamp":"2026-04-17T00:00:00","metadata":{"timeframe":"today 3-m","query_type":"interest_over_time","avg_interest":11.0}},
    {"source":"google_trends","term":"collagen drink","signal_value":9,"snippet":"Google Trends: 'collagen drink' avg interest=19.0/100, growth +9%","timestamp":"2026-04-17T00:00:00","metadata":{"timeframe":"today 3-m","query_type":"interest_over_time","avg_interest":19.0}},
    {"source":"google_trends","term":"elderberry syrup","signal_value":0,"snippet":"Google Trends: 'elderberry syrup' avg interest=28.0/100, growth 0%","timestamp":"2026-04-17T00:00:00","metadata":{"timeframe":"today 3-m","query_type":"interest_over_time","avg_interest":28.0}},
    {"source":"google_trends","term":"turmeric latte","signal_value":15,"snippet":"Google Trends: 'turmeric latte' avg interest=16.0/100, growth +15%","timestamp":"2026-04-17T00:00:00","metadata":{"timeframe":"today 3-m","query_type":"interest_over_time","avg_interest":16.0}},
    {"source":"google_trends","term":"honey wellness","signal_value":11,"snippet":"Google Trends: 'honey wellness' avg interest=8.0/100, growth +11%","timestamp":"2026-04-17T00:00:00","metadata":{"timeframe":"today 3-m","query_type":"interest_over_time","avg_interest":8.0}},
    {"source":"google_trends","term":"organic ginger shot","signal_value":130,"snippet":"Google Trends rising query: 'organic ginger shot' +130% (related to 'ginger shot')","timestamp":"2026-04-17T00:00:00","metadata":{"parent_term":"ginger shot","query_type":"rising_related"}},
    {"source":"google_trends","term":"what are ginger shots good for","signal_value":60,"snippet":"Google Trends rising query: 'what are ginger shots good for' +60%","timestamp":"2026-04-17T00:00:00","metadata":{"parent_term":"ginger shot","query_type":"rising_related"}},
    {"source":"google_trends","term":"vive ginger shot","signal_value":60,"snippet":"Google Trends rising query: 'vive ginger shot' +60%","timestamp":"2026-04-17T00:00:00","metadata":{"parent_term":"ginger shot","query_type":"rising_related"}},
    {"source":"google_trends","term":"lemon ginger shot benefits","signal_value":50,"snippet":"Google Trends rising query: 'lemon ginger shot benefits' +50%","timestamp":"2026-04-17T00:00:00","metadata":{"parent_term":"ginger shot","query_type":"rising_related"}},
    {"source":"google_trends","term":"lions mane supplement","signal_value":400,"snippet":"Google Trends rising query: 'lions mane supplement' +400%","timestamp":"2026-04-17T00:00:00","metadata":{"parent_term":"lion's mane","query_type":"rising_related"}},
    {"source":"google_trends","term":"lions mane mushroom benefits","signal_value":200,"snippet":"Google Trends rising query: 'lions mane mushroom benefits' +200%","timestamp":"2026-04-17T00:00:00","metadata":{"parent_term":"lion's mane","query_type":"rising_related"}},
    {"source":"google_trends","term":"moringa benefits","signal_value":5000,"snippet":"Google Trends rising query: 'moringa benefits' breakout","timestamp":"2026-04-17T00:00:00","metadata":{"parent_term":"moringa powder","query_type":"rising_related"}},
    {"source":"google_trends","term":"mushroom coffee benefits","signal_value":3250,"snippet":"Google Trends rising query: 'mushroom coffee benefits' +3250%","timestamp":"2026-04-17T00:00:00","metadata":{"parent_term":"mushroom coffee","query_type":"rising_related"}},
    {"source":"google_trends","term":"elderberry gummies","signal_value":5000,"snippet":"Google Trends rising query: 'elderberry gummies' breakout","timestamp":"2026-04-17T00:00:00","metadata":{"parent_term":"elderberry syrup","query_type":"rising_related"}},
    {"source":"google_trends","term":"ube powder","signal_value":1150,"snippet":"Google Trends rising query: 'ube powder' +1150%","timestamp":"2026-04-17T00:00:00","metadata":{"parent_term":"ube latte","query_type":"rising_related"}},
    {"source":"google_trends","term":"turmeric ginger tea","signal_value":150,"snippet":"Google Trends rising query: 'turmeric ginger tea' +150%","timestamp":"2026-04-17T00:00:00","metadata":{"parent_term":"turmeric latte","query_type":"rising_related"}},
    {"source":"google_trends","term":"reishi mushroom benefits","signal_value":220,"snippet":"Google Trends rising query: 'reishi mushroom benefits' +220%","timestamp":"2026-04-17T00:00:00","metadata":{"parent_term":"reishi tea","query_type":"rising_related"}},
    {"source":"google_trends","term":"ashwagandha benefits","signal_value":180,"snippet":"Google Trends rising query: 'ashwagandha benefits' +180%","timestamp":"2026-04-17T00:00:00","metadata":{"parent_term":"ashwagandha gummy","query_type":"rising_related"}},
]

with open("gt_cache.json", "w", encoding="utf-8") as f:
    json.dump({"saved_at": datetime.now().isoformat(), "signals": signals}, f)

print(f"Cache seeded with {len(signals)} signals.")
